### PR TITLE
User groups

### PR DESCRIPTION
**Pull request by Bandisa**
# Info
## Data
- So here I found json data for all known universities
- The data was cleaned using a python script to get the import fields for user sign up
- Data was exported as JSON
## Data Modelling
- The Institution, Student and Admin data models were created
- The necessary relationships were attached
- Also added a relationship that will allow us to query for students given an institution id, same for admin

# Testing
No major testing done yet
# Reason For PR
- Need to deploy the data model, so need to merge this to backend then dev and test deployment

### CODE REVIEW

**Review by u20612894 — DISMISSED** [review]
I see no issues

**Review by ShashinGounden — DISMISSED** [review]
Looks good

**Review by Tymac15 — DISMISSED** [review]
seems good to me

**Review by ShashinGounden — DISMISSED** [review]
Looks all good.

**Review by ShashinGounden — DISMISSED** [review]

**Review by u20612894 — DISMISSED** [review]

**Review by u20612894 — DISMISSED** [review]

**Review by u20612894 — APPROVED** [review]

**Review by Tymac15 — APPROVED** [review]
approved

**Review by ShashinGounden — APPROVED** [review]
Looks in order

**Pull request merged**
