### PR TITLE
Schema fix

### LINKED ISSUE #27: Finalise the database models
Please finalize the database models, updating any changes that needs to be made.

### PR DESCRIPTION
**Pull request by Bandisa**
# Info
- data model schema was modified according to the latest amplify documentation
- reconfiged auth and the api due to deployment issues
# Build
- `amplify api gql-compile` compiles the new schema accordingly
# deployement
- succeccfuly deployed the new resources, including the dynamodb table with `amplify push` on dev env
# Reason For PR
Need to merge the changes so that we can start writting queries.
# Issue
This closes #27

### CODE REVIEW

**Comment by Bandisa** [comment]
removed unnecessary auto-gen code

**Review by ShashinGounden — APPROVED** [review]
New changes looks like it makes sense.

**Review by Tymac15 — APPROVED** [review]
Looks good to me

**Comment by Bandisa** [comment]
Already merged as part of another branch

**Pull request closed without merging**
