### PR TITLE
Frontend dev

### PR DESCRIPTION
**Pull request by ShashinGounden**
Added more modules to mock data for the timetable page

### CODE REVIEW

**Review by u21598267 — APPROVED** [review]
Everything looks really good! great work!

**Review by Tymac15 — DISMISSED** [review]
Front end looks good and all functioning properly

**Review by u20612894 — APPROVED** [review]
All good

**Review by u21598267 — APPROVED** [review]
All looks good

**Review by Tymac15 — APPROVED** [review]
conflicts sorted, good to go

**Review by Bandisa — APPROVED** [review]
All set for the demo.

**Review by u20612894 — APPROVED** [review]
Seems good

**Pull request merged**
