### PR TITLE
Component design

### PR DESCRIPTION
**Pull request by Bandisa**
Draft component design and sequence diagrams.

### CODE REVIEW

**Review by u21598267 — APPROVED** [review]
Reviewed all the diagrams and think it has all been well covered! Very neat!

**Review by u20612894 — APPROVED** [review]
The diagrams are good. I approve

**Review by ShashinGounden — APPROVED** [review]
These diagrams look great and are very detailed! Should also be added to the main documentation.

**Comment by Bandisa** [comment]
> These diagrams look great and are very detailed! Should also be added to the main documentation.

Will do. Thanks.

**Pull request merged**
