### PR TITLE
Implemented UI pages

### PR DESCRIPTION
**Pull request by ShashinGounden**
Implemented the timetable page (shows module+time+venue):
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 02

Also shows when there's no modules
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 07

Implemented a simple map interface on the navigation page
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 11

Implemented search feature:
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 18

Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 14

Can select a module:
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 20

Brings up modal to select lecture and practical times:
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 24

Implemented a notification page:

Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 31

Lastly, implemented an accounts page:
Simulator Screenshot - iPhone 14 - 2023-05-20 at 00 00 24

### CODE REVIEW

**Review by Bandisa — DISMISSED** [review]
From the demo, I am happy with the progress.
Please remember to add a bit more info on the ReadMe, maybe pictures with a short description/functionality of each page?

**Review by u20612894 — APPROVED** [review]
I'm happy with the UI

**Review by Tymac15 — APPROVED** [review]
UI looks good to go

**Review by Bandisa — APPROVED** [review]

**Review by u21598267 — APPROVED** [review]
Everything looks good!

**Pull request merged**
