### PR TITLE
Component/transform schedule to standard schema

### PR DESCRIPTION
**Pull request by Bandisa**
# info
This is a proposed design for a component that will enable us to standardise uploaded schedules that have the annual or semester schedule for a specific year.

# technical details
- This components aims to leverage the `extract, transform and load principle` used in cleaning up data for analyses during `data analysis` and/or `machine learning`
- It will leverage the highly available and reliable AWS Component `AWS Glue`, in conjunction with other services as part of a unit
- The uploaded schedule will then be standardized and stored on `dynamoDB` for use with other processes such as `detecting schedule clashes`, or `querying modules for module` search by a `student`.

# NB
- A brief Proposed development timeline is included in the ReadMe.md, with more information
- This is subject to change

# Alternatives
- `Python Pandas or Polaris`, with the aid of `AWS Lambda` that will be triggered by `S3 Event Notification` or by the `S3 Bucket` directly can also be used.
- Validity to be assed upon request

### CODE REVIEW

**Review by u21598267 — APPROVED** [review]
All changes have been communicated to me. I approve the changes.

**Comment by ShashinGounden** [comment]
Looks good, as agreed for our first implementation we will use a standard template for ourselves to ensure the system is working correctly, thereafter we will use this system to standardize all university's lecture schedules.

**Review by u20612894 — APPROVED** [review]
I approve of this. It seems to simplify implementation and cover more cases

**Comment by Bandisa** [comment]
This is a stretch component, it will be implemented once we are done with our immediate  milestones.

**Pull request merged**
