### PR TITLE
Project readme for Main

### PR DESCRIPTION
**Pull request by Tymac15**
project readme

### CODE REVIEW

**Review by ShashinGounden — APPROVED** [review]
Looks great!

**Review by ShashinGounden — CHANGES_REQUESTED** [review]
The pictures aspect ratio/stretch appears weirdly on my side. Is there a way to change that?

**Comment by Tymac15** [comment]
> The pictures aspect ratio/stretch appears weirdly on my side. Is there a way to change that?

picture sizes have been changed to avoid any weird stretching

**Review by ShashinGounden — APPROVED** [review]

**Review by u21598267 — APPROVED** [review]
Looks good

**Review by u20612894 — APPROVED** [review]
Good to go

**Pull request merged**
