### PR TITLE
Front end settings pages

### PR DESCRIPTION
**Pull request by ShashinGounden**
Completed the remaining pages on the user settings page. Reset password, view account details, delete account, privacy policy etc.

### CODE REVIEW

**Review by u20612894 — DISMISSED** [review]
Looks good

**Review by Tymac15 — DISMISSED** [review]
lgtm

**Review by u20612894 — APPROVED** [review]
Seems good

**Review by Tymac15 — APPROVED** [review]
Good to go

**Review by Bandisa — APPROVED** [review]

**Pull request merged**
