### PR TITLE
initial project set-up, with dynamoDB,S3, Auth and GraphQL API

### PR DESCRIPTION
**Pull request by Bandisa**
# Info
This is the initial set-up for amplify
# What is currently set-up?
1. S3 for blobe storage and another bucket for deployment
2. DynamoDB 
3. GraphQL API, the end-points and some basic queries and autogenerated mutations
4. Authentication and user groups
5. SignUp
6. 2-factor auth
7. gitignore for env variables
8. Basic graphQL shema
# What is missing
1. Need to point amplify to div brench for auto deployment
2. Need to import the UI 
3. Change the autogen Schema to match our own
4. Add the necessary quries and mutation
5. assign user groups IAM roles for data writes and reads
6. secure endpoints.

### CODE REVIEW

**Review by u20612894 — COMMENTED** [review]
I have no issues with this but do resolve the merge conflict

**Review by ShashinGounden — DISMISSED** [review]
Was explained in yesterday's meeting. Set up looks good.

**Review by Tymac15 — DISMISSED** [review]
I agree with shahsin and Andile, looks good when you explained it thoroughly. Resolve the merge conflict but I will approve .

**Review by u20612894 — DISMISSED** [review]

**Review by u20612894 — APPROVED** [review]
Approved. All seems well

**Review by ShashinGounden — APPROVED** [review]
Great work thus far!

**Review by Tymac15 — APPROVED** [review]
good to go

**Pull request merged**
